### ISSUE TITLE
Paremmat Päivämäärät suomeksi

### ISSUE THREAD

**Issue by jpek-m** [Taapeli/stk-upload#1]
_[testi-issue]_ Päätettävä, miten esitetään avoimet aikarajaukset "–1899" ja "1900–":

- A "1899 asti" ja "1900 alkaen"
- B "ennen 1899" ja "1900 jälkeen"

A on tarkka tulkinta, mutta näyttää huonolta esim. syntymäaikana. Henkilö olisi syntynyt "ennen 1830", parempi kuin "1830 asti".

B istuu paremmin esim. asuintapahtumiin. Asuinpaikka "1850 asti" on hieman parempi kuin "ennen 1850".

Onko tässä samanlainen ero kuin "ajanjaksolla 1850...1860" ja "1850 ja 1860 välillä"?

**Comment by PeterJPower** [comment]
B-vaihtoehto tulee Grampsin käytännöstä (suomennoksesta). A-vaihtoehto on sikäli tarkempi, että siitä käy paremmin selvillä, että vvvv kuuluu mukaan. Stk-sovelluksen tulosteisiin saadaan varmaan enemmän vapautta käyttää kaunista suomenkieltä, ehkä tapauskohtaisesti mukaillenkin?

**Comment by jpek-m** [comment]
Pitänee tarjota molemmat vaihtoehdot. Jos hääpäivä on ollut "ennen 1880", ei voi sanoa "1880 asti"!

**Comment by jpek-m** [comment]
Uusi, tarkempi kuvaus #93
