### ISSUE TITLE
Toiminto "Poista kaikki tarjokasaineistoni" ei toimi ei-admin-käyttäjälle

### ISSUE THREAD

**Issue by kkujansuu** [Taapeli/stk-upload#10]
Käyttäjän "profiilisivulla" /settings on linkki "▸ Poista kaikki tarjokasaineistoni". Mutta sen klikkaaminen antaa virheen "You do not have permission to view this resource." ellei käyttäjällä ole myös admin-oikeuksia.

**Comment by jpek-m** [comment]
Termit ja toiminnot tosiaan epäselviä _Omat tiedot_ -sivulla `/settings` ja _Grampsista ladatut aineistot_ -sivulla `/gramps/uploads`. Niillä on samoja toimintoja eri nimillä.
1. _Omat tiedot_ -sivulla esiintyy sekä termit "tuontierät" että "tarjokasaineistot". Pitäisi tehdä valinta.
"Delete"-napin luulisi siellä tarkoittavan tuontierän poistoa kannasta, mutta poistaakin kai  lähdetiedoston. "Talleta aineistojasi tästä" tarkoittaa samaa kuin "Tuo uusi Gramps-tiedosto" _Grampsista ladatut aineistot_ -sivulla.
3.  _Grampsista ladatut aineistot_ -sivulla on käytetty sarakeotsikkoa "XML-tiedosto" viittaamaan nimenomaan tuontierän Gramps-lähdetiedostoa ja siellä on myös nappi "Poista tiedosto" tekemään  deleten

Ehdotan, että termit **tuontierä** ja/tai **tarjokasaineisto** ovat nimenomaan tietokannan termejä, ladattu Gramps xml-tiedosto on **lähdetiedosto** tai **Gramps-tiedosto**.

**Comment by jpek-m** [comment]
"Poista kaikki tarjokasaineistot" on poistettu /settings -sivulta, ei kuulu sinne. Yksittäisten tarjokasaineistojen poisto on /gramps/uploads -sivulla
