### ISSUE TITLE
Paikat-muunnokseen merkkijonon korvaus

### ISSUE THREAD

**Issue by kkujansuu** [Taapeli/stk-upload#12]
PekkaV 25.5.2019:

tuli vastaan gedcom, jossa paikat on kirjattu erotettuna
kenoviivalla, esim. "Uusikirkko/Iivattala". Paikat-työkalussa on jo
muunnos, jolla välilyönnit vaihdetaan pilkkuun, Voisiko siihen lisätä
kiinteästi "Vaihda välilyönnit tai kenoviivat pilkkuun"? Tai vielä
geneerisempi olisi ratkaisu, jossa olisi avoin syöttökenttä Vaihdettava
merkki = "  " , joka korvataan pilkulla. Näitä erottimia voi nimittäin
tulla eteen jatkossa muitakin.

**Comment by kkujansuu** [comment]
Riittäisikö tekemäni Gramps-lisäosa "PlaceTool", jolla voi tehdä mielivaltaisia merkkijonokorvauksia?

**Comment by PeterJPower** [comment]
Riittää mainiosti. Tänään muuten taistelin Maaritin Pirkkala-kannan lähteiden kanssa. Oli jostain syystä kirjannut jokaisen lähdeviittauksen omalle lähteelleen. Osassa lähteen nimessä oli perässä osa/rivi -tieto ja Lainaus oli tyhjä. Gramps osaa yhdistää lainaukset, muttei lähteitä. Jos sen toteuttaisi, ehdoksi voisi laittaa että vain Nimike+ID kentissä on tietoa.
