### ISSUE TITLE
Tarjokasaineiston XML-tiedoston lähetysvalinnassa suodatus ei toimi

### ISSUE THREAD

**Issue by Juha42** [Taapeli/stk-upload#14]
Aineiston lähettäminen -> Selaa... -nappulasta avautuvan tiedostonvalintaikkunan alareunassa oleva valintanappula sisältää tekstin "Kaikki tiedostot v" (nuoli alas, ikäänkuin pudotusvalikko).  Pudotusvalikko ei vain toimi.  Olisi siistiä, jos siitä voisi valita esim. .gramps -tyyppiset tiedostot (joka ehkä voisi olla jopa oletuksena?)

**Comment by kkujansuu** [comment]
Korjattu

**Comment by Juha42** [comment]
Oli nopeasti.
