### ISSUE TITLE
Yhtaikaiset Neo4j-lataukset sotkevat toisensa

### ISSUE THREAD

**Issue by kkujansuu** [Taapeli/stk-upload#15]
Lisättävä lukitus, jotta lataukset menevät peräkkäin

**Comment by jpek-m** [comment]
Vastasin väärässä rihmassa: https://github.com/Taapeli/stk-upload/issues/9#issuecomment-511210846

**Comment by kkujansuu** [comment]
Sotkee ne mun nähdäkseni ainakin sen verran että yhtaikaisille latauksille voi tulla sama batch-id (esim. 2019-07-14.001)

**Comment by kkujansuu** [comment]
Korjattu commitissa 7e20bd5  (Batch id generation fix).
