### ISSUE TITLE
/scene/source - Lähteeseen liitetyt tapahtumat

### ISSUE THREAD

**Issue by jpek-m** [Taapeli/stk-upload#16]
_PekkaV:_
Isotestissä https://isotest.isotammi.net/scene/source=87723 on lähteen nimen (**Hämeenlinna ksrk syntyneet 1850-1874**) alla Narc-linkki **sivuun 347**. Linkin pitäisi olla ao. sivun kohdalla ja lisäksi puuttuu linkki sivuun 342. Se on mukana Sibeliuksessa.

1. Sivun yläosassa on otsikon alla linkki narcin yhteen kuvaan, mutta linkkihän ei koske koko lähdettä vaan yhtä sivua
2. Alaosassa kuhunkin sivuun ("**C3315 Sivu s. 342**") on lisättävä vastaava linkki ko sivun kuvaan
3. Sivun otsikko on väärä, korjattava kaikilla kielillä. "Lähteeseen liitetyt tapahtumat", po. "Viittaukset lähteeseen". (Kaikki viittaukset ei ole tapahtumista, esim. https://isotest.isotammi.net/scene/source=85893 , "Sivu s. 75 1872 Huhtikuu 22" sisältää viittauksen Person-nodesta)
4. Voisihan lähteen nimen alle laittaa rivin "Tunnus 1234 / S4567" (Malli Henkilö-sivulta)

**Comment by kkujansuu** [comment]
Oliskohan tämä oikea linkki: https://isotest.isotammi.net/scene/source=112628

**Comment by jpek-m** [comment]
Siis linkki lähde-kuvaan puuttuu

**Comment by jpek-m** [comment]
Sitaatin kohdalla on voi olla 1) viittauksia tapahtumasta muotoa "nimi tapahtuma" ja 2) viittauksia henkilöstä "nimi \~". 
Siellä näkyy myös pelkkä "\~", joka näyttää olevan viittaus henkilönnimestä. Tätä voisi jotenkin täydentää niin että tulee ymmärrettäväksi
