### ISSUE TITLE
Gedcom-tiedoston avaaminen ei onnistu

### ISSUE THREAD

**Issue by jpek-m** [Taapeli/stk-upload#17]
Ohjelma kaatuu kohdassa  **bp/gedcom/transforms/model/surnameparser.py, line 3**, kun valitsee käsiteltävän tiedoston sivulla `/gedcom` :

**ModuleNotFoundError: No module named 'dataclasses'**

**Comment by kkujansuu** [comment]
Erikoista, moduli 'dataclasses' pitäisi olla mukana Python-versiossa 3.7: https://docs.python.org/3/library/dataclasses.html. Onko tämä sinun omassa kehitysympäristössäsi?
