### ISSUE TITLE
.pydevproject pois versionhallinnasta

### ISSUE THREAD

**Issue by kkujansuu** [Taapeli/stk-upload#2]
Tämä on kokeeksi tehty "issue" (mutta mielestäni ihan oikea ongelma).

Tiedosto .pydevproject ei ehkä saisi olla versionhallinnassa (t.s Githubissa). Kun teen pull-operaation, niin siellä oleva versio korvaa oman versioni, jossa on mm. polku oikeaan Python-tulkkiin (käytän virtualenvissä olevaa Pythonia). Nyt joudun aina pullin jälkeen korjaamaan ko. polun Eclipsessä. Kommentteja?

Tämän tiedoston nimen voi varmaan panna joko tiedostoon .gitignore tai .git/info/exclude (jota kai oletuksena ei ole olemassa). En tosin tiedä miten sen saa pois Githubista kun se siellä jo on.

**Comment by jpek-m** [comment]
Kannatan. Luulin sen jo lisänneeni .gitignoreen, tee sinä

**Comment by kkujansuu** [comment]
Lisäsin ja tein commit-and-push, mutta ei se silti ilmesty githubiin (siis uusi .gitignore-tiedosto)!??? Eikä ko. commit edes näy githubissa.

Poistin .pydevprojectin käsipelillä githubista (web-liittymästä), mutta se ehkä tulee sinne uudestaan kun joku tekee pushin?

Voin tietysti vielä editoita .gitignorea web-liittymän kautta. Olisikohan se hyvä idea? No oli tai ei, niin tein sen jo.
