### ISSUE TITLE
Lähdeviitteet ei mene oikein jos lainauksella on useampia lisätietoja

### ISSUE THREAD

**Issue by kkujansuu** [Taapeli/stk-upload#20]

**Comment by kkujansuu** [comment]
Esim. Linda Sibelius:
https://isotest.isotammi.net/scene/person=100115
https://isotammi.net/scene/person=240866

**Comment by jpek-m** [comment]
![neo4j bolt localhost 2019-09-15 - Neo4j Browser](https://user-images.githubusercontent.com/9086853/64925960-8b4a1b00-d800-11e9-9134-6bf242580b8d.png)
Tässä Linda Siveliuksen Note- ja Citation-yhteydet.

**Comment by jpek-m** [comment]
Kysymys olikin alla olevasta tilanteesta: käsittelyssä ei huomioida **Citation**-nodeen liittyviä **Note**-tietoja. Olisi luultavasti hallittavissa person-sivulla (versio 2) vain templatea korjaamalla.
![Screenshot_2019-09-15 neo4j bolt localhost 7687 - Neo4j Browser](https://user-images.githubusercontent.com/9086853/64927279-5abead00-d811-11e9-87c9-a826ab159dff.png)

**Comment by jpek-m** [comment]
Henkilösivun v3 työnä jatkuu
