### ISSUE TITLE
Lähteen metatiedot Isotammessa

### ISSUE THREAD

**Issue by PeterJPower** [Taapeli/stk-upload#27]
Maija Salon kirja on ensimmäinen "kirja" tyyppinen lähde. Katselin siksi ajatuksella, mitä lähdeviittauksista ohjeistetaan yliopistoissa. Esim. [Jyväskylä ](url)https://koppa.jyu.fi/avoimet/kirjasto/kirjastotuutori/lahteet-hallintaan/lahteet-viittaukset/nain-viittaat

Siitä nousi seuraava kehitystavoite:

Nyt Grampsista Isotammeen siirretään (tai ainakin hyödynnetään) lähteen metatiedoista vain nimi.  Käsittelemättä jäävät tiedot, joita tarvitaan hyvässä lähdeviittauskäytännössä: Tekijä, Julk.info, Lyhennys ja Arkisto. Tällä on merkitystä etenkin kirja-lähteiden osalta. Esim.  lähdeviittaus Maijan kirjaan, jossa Lyhennys on "Salo 2017", olisi muotoa "Salo 2017:15-20", jos viitataan kirjan ko. sivuihin.

Tieto siitä, että Maijan kirja on "kirja", löytyy Grampissä itse asiassa sen Arkisto-sivun kautta, Mediatyyppi="Kirja". 

Tavoite olisi aluksi, että Isotammen Lähteeseen lisätyt tapahtumat-sivussa näytetään lähdetasolla em. puuttuvat metatiedot, mediatyyppi ja Arkisto. Arkisto olisi hyperlinkki uuteen Arkisto-lehteen, johon olisi koottu kaikki arkistosta kirjatut tiedot (ml. osoite) sekä jossa listattaisiin kaikki arkistossa olevat lähteet.

**Comment by jpek-m** [comment]
Olisi parasta saada esimerkki, jossa lähteeseen on merkitty kaikki tarpeelliseksi nähtävät kentät. Sitten voidaan suunnitella niiden tallettamista kantaan ja näyttämistä sivulla.

**Comment by PeterJPower** [comment]
Esimerkki: Maijan kirja hänen Gramps-kannassaan:

Nimike:  Affleck - Skottlantilainen suku Suomessa
Tekijä: Maija Salo
Julk. info: 2017 DoD ISBN xxxxxxxxxxxx
Lyhennys: Salo 2017
Arkistot: Kansalliskirjasto ja SSS:n kirjasto

Huomattava on, että lähteeseen voi siis liittää monta arkistoa. Tuo "2017 DoD" on painolaitos ja vuosi. ISBN on kaikkien julkaisujen ID.

**Comment by jpek-m** [comment]
Metatiedot tiettävästi talletetaan, mutta niiden näyttämistä ei ole toteutettu

**Comment by jpek-m** [comment]
Sibelius-aineistoon testitapauksia!
Lähdetyypin kirjaaminen on vähän heikkotasoista

**Comment by PeterJPower** [comment]
11.9. uusimpaan versioon Sibeliusta on korjattu lähdetyypit. Genos-lehdet -arkistossa on 7 artikkelia, joiden metadata on kunnossa. Painoteokset-arkistossa on niitä 12 lisää.

[https://drive.google.com/file/d/1RXvEwIA5YEcsUuba1c0Rzl6pmzq9KfAC/view?usp=sharing](url)
