### ISSUE TITLE
Uuid:n käyttö Neo4j:n id():n tilalla

### ISSUE THREAD

**Issue by TimNal** [Taapeli/stk-upload#3]
Neo4j:n id()-funktion käyttö ja id-tiedon tallettaminen saattaa johtaa ajoaikaisiin virhetilanteisiin

https://neo4j.com/blog/dark-side-neo4j-worst-practices/

**Comment by jpek-m** [comment]
Kyllä, tämä on huomioitava, meilläkin poistetaan suuria määriä dataa (tuontieriä). (Testiympäristössähän en ole nähnyt tunnisteiden uudelleenkäyttöä, kun aineistot on pieniä.)

Olisiko ratkaisu se, että Cypher-lauseissamme yksinkertaisesti (!?) kaikki _uniq_id_ -viittaukset `ID(person)` jne. korvattaisiin ilmaisulla `person.handle` ?

Meillä on nyt käyttöliittymässäkin monessa paikassa _id_ näkyvissä, jotta käyttäjä voi vaikka kirjoittaa ylös tai silmällä seurata, mitkä on samoja ja mitkä eri objekteja. Periaatteessa siihen tarkoitukseen voisi käyttää `handle`:n 4 ensimmäistä tai viimeistä merkkiä kuten git tekee. Tai vaikka yhdistelmää` person.id + '-' + handle[-4:]` : `I0023-47ec`

**Comment by TimNal** [comment]
Kyllä, tekniset riskit on vältettävissä vaihtamalla uniq_id:n käsittely handleen kohdistuvaksi.

Toinen kysymys on tuo käyttäjäystävällinen tunniste, jonka Gramps on ratkaissut objektityyppikohtaisella numeroinnilla. Tunniste on yksikäsitteinen sukupuun sisällä, Grampsissa ainoastaan lisätään samaan sukupuuhun. Meillä mietittävää tulee tilanteessa, jossa stk:ssa kaksi eri sukupuuta yhdistetään ja tunnisteet voisivat 'törmätä', ellei tunnuksia ole suolattu jollakin riittävän satunnaisella. Handlen osa kuulostaa sinällään hyvältä. Tutkijan kannalta etuna olisi, että tunniste voidaan säilyttää myös yhdistetyssä sukupuussa. Pienenä ongelmana voi nähdä sen, että yhdistetyn sukupuun objektien lajittelussa eri sukupuista tulleet ovat  peräkkäin samalla alkuosalla, vaikkei niillä ole keskenään mitään yhteyttä. Auttaisiko, jos handle-pala olisi keulilla: I47ec-0023 ? Toisaalta lajittelujärjestys voi tilanteesta riippuen olla jokin muukin.

**Comment by jpek-m** [comment]
Tämä otettaneen työn alle, kun meneillään oleva tietokantaluokkien järjestely saadaan tehtyä, en yrittäisi yhtäaikaa.

Entä jos meillä olisi tuontierän järjestysnumero? Näyttötunniste voisi olla vaikka `'I0042-0034'` (erälle 42). Tai jos ei haluta paljastaa juoksevaa eränumeroa, sen voi kevyesti häslätä.

**Comment by kkujansuu** [comment]
Käytetään UUID:tä.

**Comment by jpek-m** [comment]
Kaikki scene/route.py -sivut muutetaan käyttämään uuid:tä eikä uiq_id:tä. Esim.` /scene/person/uuid=<pid>` korvaa entisen `/scene/person=<int:pid>`

**Comment by jpek-m** [comment]
Toteutus: urleissa aina uuid, mutta sivun koostamisen aikana yhteydet perustuvat yleensä uniq_id:hen, joka on kaikkei tehokkain
