### ISSUE TITLE
Tuoreen henkilötiedon suojaaminen

### ISSUE THREAD

**Issue by jpek-m** [Taapeli/stk-upload#34]
**Tarkennettava sääntö:** Henkilön tietoja ei saa näyttää, jos:

1.  kuolemasta alle 50 vuotta _tai_
2. syntymästä on alle 125 vuotta

Tämä sääntö on koodattava jokaiselle henkilötietoja näyttävälle sivulle.

**Tutkija** näkee myös nämä rajatut tiedot merge-toiminnon yhteydessä

**Comment by kkujansuu** [comment]
Tuo sääntö ei liene ihan oikein. Sen mukaanhan tietoja ei saisi näyttää jos henkilön elinvuodet olivat esim. 1900-1901 (ehto 2 toteutuu).

Parempi sääntö on ehkä:

1. (kuolinaika tiedetään ja) kuolemasta alle 50 vuotta 
tai 
2. kuolinaikaa ei tiedetä ja syntymästä on alle 125 vuotta

**Comment by PeterJPower** [comment]
Paranee. Otettaisiinko huomioon sekin tilanne, että henkilöllä ei ole kumpaakaan aikaa ja vanhemmista voi päätellä henkilölle syntymäaikaa? Esim. äidin syntymä+45 vuotta.

**Comment by jpek-m** [comment]
Sääntö henkilö [oletettavasti] kuollut. Perustuu henkilölle laskettuun mahdollisesti arvioituun elinaikaan
Done
