### ISSUE TITLE
Kuvat ja muu media-sivu ei näytä mitään

### ISSUE THREAD

**Issue by PeterJPower** [Taapeli/stk-upload#36]
Anna Kirvesniemeen (Affleck-tarjokasaineistossa) on liitetty hautakiven kuva ja se näkyy Annan henkilökortilla. Ei näy kuitenkaan Kuva ja muu media-sivun kautta.

**Comment by PeterJPower** [comment]
Isotammessa siis. En muistanut katsoa tilannetta Isotestissa.

**Comment by jpek-m** [comment]
Done
