### ISSUE TITLE
Gedcom-analyysi: enemmän kuin 10 rivilinkin näyttö

### ISSUE THREAD

**Issue by kkujansuu** [Taapeli/stk-upload#4]
Yhdellä rakennevirherivillä on nyt max. 10 rivinumeroa ja niiden perässä ",...".  Olisiko mahdollista/järkevää tehdä viimeiseksi myös linkki, joka avaisi esim. 100 rivinumeron linkkilistan
tai 10 seuraavaa askeltaen?

**Comment by jpek-m** [comment]
Hyvä ajatus. Virhenumeroita voisi olla selvästi vähemmän kuin kymmenen, jotta mahtuisi riville useammin. Jos perässä on linkki, ei ole tarvetta kovin moneen numeroon. 
Linkistä voisi laajentaa rivin niin että kaikki numerot on näkyvissä?

**Comment by jpek-m** [comment]
Ei tärkeä
