### ISSUE TITLE
Gramps XML-tiedoston sisäänluku toimimaan myös .xml-tiedostoille

### ISSUE THREAD

**Issue by kkujansuu** [Taapeli/stk-upload#42]
1. Myös .xml -päätteiset tiedostot hyväksytään
2. gramps_loader.py", line 368, in _clean_apostrophes: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 512: invalid start byte

**Comment by jpek-m** [comment]
Ohjalemavaihe cleanapostrophes voi olla turha. Koordinaateissa voi olla parittomia heittomerkkejä, mutta grampsin tulisi ne hoitaa. Tämän voisi tarkastaa.
