### ISSUE TITLE
Businesluokkien kyselyn json-rajapinta

### ISSUE THREAD

**Issue by jpek-m** [Taapeli/stk-upload#46]
Kehitetään yhdenmukainen `json_encode`-metodi, jolla `bl`-luokkien tiedot voidaan välittää javascript-ohjelmille ja käyttöliittymään.

Mahdollistaa dynaamisten sivujen luonnin Vue-teknologialla, esim. nappi jolla voi valita tapahtuman paikan aukeavassa konnahdusikkunassa.

Ks. luonnostelua [Jsonin tuottaminen Stk-luokista](https://docs.google.com/document/d/1C6LznowGlE8u2inRnyV19KXtdkyXXoIJSNVwQ8G9ifI/edit#)

**Comment by kkujansuu** [comment]
Panin vähän lisäkommenttia ym. dokuun,

**Comment by jpek-m** [comment]
Toteutettu `NodeObject`:iin ja erikseen `DateRange`:een, toiminee kaikkialla
