### ISSUE TITLE
Tekstikentän muokkausikkuna

### ISSUE THREAD

**Issue by jpek-m** [Taapeli/stk-upload#50]
Tehdään ponnahdusikkuna jonkin **tekstikentän** muokkaamiseksi.

**Comment by jpek-m** [comment]
Aloitetaanko ammattikentästä?

**Comment by kkujansuu** [comment]
Voisi ehkä myös olla että yksinkertaisten kenttien editointiin ei tarvita varsinaista "ponnahdusikkunaa", vaan voisi riittää että staattinen tekstikenttä muuttuu editoinnin ajaksi input-kentäksi (textbox). Kuten esim. siinä mun aiemmin tekemässä dbeditor-kokeilussa (https://isotest.isotammi.net/dbeditor/):
![Selection_421](https://user-images.githubusercontent.com/17925982/91062561-8a874f00-e635-11ea-9893-763e28275a21.png)
![Selection_422](https://user-images.githubusercontent.com/17925982/91062557-89562200-e635-11ea-9171-86a9c0782d11.png)

**Comment by jpek-m** [comment]
Uusi tehtävä #58
