### ISSUE TITLE
Henkilön titteli mukaan

### ISSUE THREAD

**Issue by jpek-m** [Taapeli/stk-upload#51]
Kaksi tehtävää:

- Gramps-lataukseen kaikki henkilön kentät
- Näytetään henkilö-sivulla

**Comment by jorma-h** [comment]
Katson huomenna. Taitaa mennä pari viikkoa.

**Comment by jorma-h** [comment]
Grampsin ohjeissa Nimien yhteydessä sanotaan:

Title
A title given to this person. Titles often accompany names on all official documents, eg Sir, Dr., ...

Mielestäni esim. seuraavat merkinnät eivät ole titteleitä:

**Comment by jorma-h** [comment]
talollisen tytär, ruustinna, profeetta, puoskari vanki, murhamies, nuori neito, eversti, mestari, kamreeri, pääjohtaja, isännöitsijä, vapaaherra, kreivi, sairaanhoitaja, merikapteeni, jne

Mutta ehkä nämä:
tasavallanpresidentti, arkkiatri, arkkipiispa, ylipuutarhuri, jne

**Comment by elandal** [comment]
Tittelin tulrr olla virallinen puhuttelumuoto joka perustuu myönnettyyn arvonimeen tai vastaavaan. Arvonimiin liittyy myöntämistapahtuma jossa arvonimi kokonaisuudessaan ilmaistaan.

En tiedä mikä on virallinen puhuttelutitteli aatelisarvojen kuten kreivi kohdalla. Espoon pitäjänkokousten pöytäkirjoissa 1700-luvun lopulla paroni jne A H Ramsay kirjattiin "Baron Ramsay". "Paroni" voisi näinollen olla titteli. Ramsaylla oli kuitenkin lukuisia arvonimiä ja käytetty titteli varmasti riippui tilanteesta. Monia arvonimiä omaavien kohdalla nimi- ja titteliasiat saattavat mennä monimutkaisiksi, eikä yksinkertainen nimi–titteli -yhteys kuten Grampsissa ole mitenkään kattava puhuttelumuoto.

Oppiarvot ovat myös arvonimiä. Esim. kirkkoherran virallinen puhuttelumuoto voi olla Kyrkoherde och Magister, joista ensimmäinen on ammatti ja toinen arvonimi. Arkkipiispakin on ammatti, mutta arkkipiispalla varmasti on myös arvonimi tai useampi, vähintään oppiarvo.

Muuten listassa näytti olevan ammatteja (Ammatti-tapahtuma) sekä yhteiskunnallista asemaa ilmaisevia termejä. Yhteiskunnalliselle asemalle ei Grampsissa ole kenttää. Voidaan kirjata esim. tapahtuman lisätietoihin, sekä milloin viitataan lähteeseen jossa sellainen on mainittu.

Virallinen puhuttelumuoto jota Titteliin kirjataan ei siis ole helposti pääteltävissä. Mitä tahansa se onkin, sen on oltava lähteistetty siten, että kyseistä muotoa tiedetään käytetyn virallisissa asiayhteyksissä.

**Comment by jpek-m** [comment]
Titteliasiaa on varmaan aihetta **ohjeistaa** Gramps-käyttäjille. 

Sovelluksen kannalta riittänee, että titteli otetaan vastaan ja näytetään ainakin henkilösivulla (ja tarvittaessa muokataan). Saattaisi olla hyvä laittaa **titteli näkyviin** myös ainakin joissakin henkilölistossa, esim. perheenjäsenissä

**Comment by PeterJPower** [comment]
Mietin tuota käyttäjien ohjeistamista. Tuntuu siltä, että on hoidettava Koulutus-, Oppiarvo-, Valmistujainen- ,Ammatti- tai Luottamustoimi-tapahtumilla "tittelit", joilla on alkamis pvm ja/tai paikka. Titteli jää mielestäni kohteliaisuus-, arvostus- tai puhuttelukäyttöön.  Titteli sopii  myös perintönä tulleen aatelisarvon (kreivi) tai valtion myöntämän arvonimen (vuorineuvos) tallentamiseen.

**Comment by jpek-m** [comment]
Näköjään titteli on nyt mukana, liittyen nimivaihtoehtoihin. Esimerkki osoittaa vääräksi, ettei kukaan olisi seppä syntyessään!
`(:NAME {"firstname": "Jaakko", "surname": "", "prefix": "", "suffix": "Pietarinpoika", "type": "Birth Name", "title": "seppä", "order": 0  })`

Henkilösivulla titteli siis näkyy nimivaihtoehdoissa, Muutin näyttömuotoa niin, että käytetään `class="typedec"` eli se näytetään pölkkykirjaimin. 

("Seppä" poikkeaa suosituksesta.) Jos on monta nimeä, tulisi siis liittää siihen nimeen, joka on ollut käytössä kun arvonimi tms. myönnettiin.

**Comment by jpek-m** [comment]
Titteli on lisätty 2021.1-versiossa. 

- Ratkaisussa on Grampista periytyvä ongelma, että titteli liittyy nimiversioon eikä henkilöön.
- Tittelin määritelmää on tarkennettava: miten se liittyy elämänvaiheisiin
