### ISSUE TITLE
Tekstien asemointiongelma scene/person -sivulla 

### ISSUE THREAD

**Issue by Juha42** [Taapeli/stk-upload#52]
Taitaa olla selaimen oletusfontista tai zoom-asetuksesta riippuva ominaisuus:

![kuva](https://user-images.githubusercontent.com/52496356/91051581-fa430d00-e628-11ea-834f-53e030d41215.png)

Voi esiintyä muillakin sivuilla.  Yhtenäinen ulkoasu antaisi paremman vaikutelman...

**Comment by jpek-m** [comment]
"Origin from:" teksti siirretty layoutilta person-sivun <h3>:n eteen.
