### ISSUE TITLE
Tilaan rekisteröidään Lisätieto sitä edeltävästä rek.nrosta 

### ISSUE THREAD

**Issue by PeterJPower** [Taapeli/stk-upload#56]
Paikkakantojen kerääjiä on ohjeistettu tallentamaan tilan nimeen myös se tilanumero, josta tilan on erotettu. Esim. "Hällinmäki 19 (11) Ellilä" tarkoittaa, että tilan nimi on "Hällinmäki 19 Ellilä" ja että tila on muodostettu, kun Hällinmäki 11 jaettiin isossajaossa. Edellinen rekisterinumero on usein merkitty rippikirjaan, joten sen tallentaminen on näin helppoa.
Vaihtoehtoinen tapa olisi ollut ohjeistaa, että paikan lisätietoon talletetaan ko. tieto edeltävästä tilasta, mutta ohjeistamani tapa on tehokkaampi tallentajan kannalta.
Edeltävien numeroiden avulla on mahdollista myöhemmin lisätä Isotammeen kyselyitä tilojen muodostumisketjuista.
Ehdotan, että ensi vaiheessa Isotammeen lisätään vain toiminallisuus, jossa edeltävästä tiedosta generoidaan paikkaan vain Lisätieto, joka alkaa avainsanalla "Edeltävä:" ja jonka perään sen nimi "Hällinmäki 11".

**Comment by jpek-m** [comment]
Ei toteuteta näin
