### ISSUE TITLE
Hiskin pappisluetteloiden lisäys Seurakunnan yhteyteen

### ISSUE THREAD

**Issue by PeterJPower** [Taapeli/stk-upload#57]
Seurakunnista ja muista kirkollisista organisaatioista löytyy Google Drivestämme ../Data/Paikkojen referenssikannat-kansiosta gramps-kanta "Kirkolliset hierarkiat 2" https://drive.google.com/file/d/1rXPb8IZLKlrnnFkSy3RzEzvVFLXn6yn6/view?usp=sharing 
Kanta kaipaa sisällöllistä kehittämistä, mutta se on periaatteessa samanlainen ladattava/kyseltävä "organisaatioiden" paikkakanta kuin varsinaisessa maantieteellisissä paikossakin.
Käyttäjiltä on tullut ehdotus, että kantaan lisätään seurakunnan yhteyteen Hiskin seurakunnan lisätietoista löytyvän Pappisluettelon henkilöt viranpidon rajavuosineen. Ks. esim. Anjala http://hiski.genealogia.fi/seurakunnat/srk?CMD=PRIESTS&ID=12&TYPE=HTML&LANG=FI.
Ko. henkilöt on liitettävissä seurakuntaansa Ammatti-tapahtumalla. Ehdotan selvitettäväksi, löytyisi Hiskin ao. luettelot suoraan tiedostona, joista generoisi tapahtumat. Muuten pitää mennä manuaalisemmin eteenpäin.

**Comment by jpek-m** [comment]
Ei toteuteta näin
