### ISSUE TITLE
Parannettu liittymisprosessi

### ISSUE THREAD

**Issue by jpek-m** [Taapeli/stk-upload#59]
1. Rekisteröityminen https://isotest.isotammi.net/register
   - luodaan käyttäjätunnus
   - lähetä vahvistuslinkki

2. Vahvistus: käyttäjä klikkaa vahvistuslinkkiä (https://isotest.isotammi.net/join ilman user, email -tietoja)
   - K. täyttää liittymislomakkeen
   - sähköposti adminille

3. Admin hyväksyy
   - K. saa asialliset oikeudet
   - sähköposti käyttäjälle

4. K. kirjautuu normaalisti

A. Miten Flask-security sallisi sähköpostin muuttamisen myöhemmin, idea [github](https://gist.github.com/Jaza/86096b4b0e933644cdf3bcc6e798c431)
   Ehkä näin:
   - käyttäjä antaa uuden sähköpostin
   - hänet kirjataan ulos
   - lähetetään vahvistuslinkki muten (1):ssä
   - vahvistuksessa sähköposti vaihdetaan User-nodeen

**Tehtävät**
* Timo tarkastaa yhteensopivuuden Flask-securityyn
* Korjataan suomenkieliseksi (Babel puuttui)

**Comment by kkujansuu** [comment]
Olen nyt tehnyt tässä kuvatun muutoksen rekisteröitymiseen. Se ei vielä ole Githubissa - ajattelin että käydään se vielä yhdessä läpi. Tämä ei sisällä käyttäjän sähköpostiosoitteen vaihtamista.

Muutoksia:

Kirjautumattoman käyttäjän etusivulla oleva "Liity mukaan"-linkki johtaa nyt rekisteröitymissivulle /register, ei enää sivulle /join.

Kirjautumissivulta poistettu erillinen "Hae käyttäjäksi"-linkki (-> /join), nyt siellä on vain "Rekisteröidy".

Rekisteröitymissivulta poistettu teksti
    "Voit rekisteröityä vain jos olet saanut kutsun. Voit ilmoittautua halukkaaksi sivulla Liity Isotammeen."

Kun käyttäjä klikkaa rekisteröintinappia
- luodaan käyttäjä (User-solmu sekä vastaava UserProfile-solmu)
- käyttäjälle annetaan rooli "to_be_approved" ja User-solmu linkataan vastaavaan Role-solmuun
- ko. Role-solmu luodaan sovelluksen alustuksessa jos sitä ei ole ennestään olemassa
- tämä rooli ei kuitenkaan näy käyttäjän päivityssivulla
- käyttäjälle lähetetään rekisteröitymisen vahvistussähköposti. Tämän saa käyttäjän omalle kielelle, kun kirjoitetaan käännökset flask-securityn käyttämille vakioteksteille.

Kun käyttäjä klikkaa vahvistuspostissa olevaa linkkiä, kirjautuu hän automaattisesti sisään ja joutuu automaattisesti sivulle /join, jossa häneltä kysytään tarkempia tietoja. Sivu on käyttäjän kielellä.

Tässä vaiheessa, kun käyttäjällä on vain rooli 'to_be_approved', käyttäjä voi siis kirjautua mutta voi mennä ainoastaan /join-sivulle, omalle profiilisivulleen (ja vaihtaa kieltä) tai sivulle, jolta voi lähettää sähköpostia adminille (paitsi jos sovelluksessa on sivuja, jotka ei vaadi mitään roolia - ja niitähän on, nämä reiät pitänee paikata!)

Ym. lomakkeen lähettämisestä lähtee adminille sähköposti, jossa on mukana linkki 

  'Approve user: https://<host>/admin/update_user/<username>'

joka vie adminin suoraan käyttäjän muokkaussivulle, jossa hän voi antaa tarvittavat oikeudet (roolit). Käyttäjän päivityssivua on muutettu niin että jos kyseessä on  'to_be_approved-käyttäjä', niin napin "Update user" sijasta onkin "Approve user", joka aiheuttaa sen että to-be-approved -rooli poistetaan.

Käyttäjän hyväksymisestä lähtee käyttäjälle automaattisesti sähköposti, jossa kerrotaan hyväksymisestä:

    otsikko: Isotammen käyttäjätunnus hyväksytty
    viesti:  Käyttäjätunnuksesi <tunnus> on nyt hyväksytty palveluun <http://host>

Tämän viestin sain menemään käyttäjän kielellä, vaikka ko. koodi tuntuu vähän kikkailulta (löytyi stackoverflowsta).

Käyttäjä voidaan hyväksyä myös "etukäteen", ennen kuin käyttäjä on vahvistanut rekisteröitymistään. Tällöin käyttäjä pääsee kirjautumaan heti vahvistuksen jälkeen eikä hänen tarvitse vastata /join-sivulla oleviin kysymyksiin!

Solmut 'Allowed_email' lienevät tämän muutoksen jälkeen tarpeettomia.

**Comment by kkujansuu** [comment]
Vein nyt nämä muutokset kuitenkin master-haaraan Githubissa, commitit 52c7201b71aaabede7130e80539d78eb4cdae652, 00ca4f9f62fcb58b64342d6f13e95ab3b81bf8d1 ja 425301627139d27ece0a98353ef68cba9b820b56.

**Comment by kkujansuu** [comment]
Huom. Jotta uusi rekisteröitymisproseduuri toimii, pitää ensin lisätä tietokantaan noodi "to_be_approved"-roolia varten. Tämä olisi varmaan pitänyt tehdä automaattiseksi, mutta lisäsin sen tietokannan alustustoimiin. Admin-käyttäjä voi ne tehdä klikkaamalla "Virkistä"-linkkiä adminin etusivulla. Ks.kuva.

![image](https://user-images.githubusercontent.com/17925982/95100927-4a3de500-073a-11eb-805b-0508489b7b31.png)

**Comment by Juha42** [comment]
Kun testasin omassa kehtysympäristössä: 1) ensin admin-roolissa 'virkistä', 2) kirjaudun ulos, 3) uudestaan kirjautumissivulle 4) rekisteröidy (tunnuksella jt); tästä singahti sähköposti, jossa mukana vahvistuslinkki. 5) kurkkasin admin käyttäjänä ja näkyi käyttäjä jt, roolissa to_be_approved, mutta en tehnyt mitään (kirjauduin ulos) 6) klikkasin sähköpostin linkkiä, 7) päädyin sivulle joka kyselee tietoja, täyttelin niitä ja painoin lähetä.  Tässä vaiheessa kai admin-käyttäjälle olisi pitänyt tulla sähköpostia; eipä tullut. config.py:ssä minulla on ADMIN_EMAIL_TO asetettu. 8) Kirjauduin  admin roolilla ja löysin "approve user", ja annon samalla research-roolin uudelle käyttäjälle. Tästäkin kai olisi pitänyt tulla postia; eipä tullut. 9) Uusi käyttäjä pääsee kirjautumaan.

**Comment by Juha42** [comment]
Korjaus: vaiheessa 7) täytetyn kyselylomakkeen palauttaminen lähettikin sähköpostia.  Minulla vaan on filtteri, joka lajittelee jollain säännöillä saapuvaa posta eri arkistolaatikoihin, ja tämä ei ollut jäänyt inboxiin, vaan meni hiukan sivummalle.  Vietissä on mukana linkki "Approve user: <linkki>", joka  vie oikeaan paikkaan.

Vaiheen 8) sähköpostitkin lähtee, mutta menee minulla spammifiltterin toimesta roskiin, koska "osoitteita on väärennetty". Minulla From ja Reply To: stk.sukututkimusseura ja isotammi.tsto.  Siis itseaiheutettu ongelma.

Summa summarum: toimii. Ja toimii loogisesti.  Minun puolesta issuen saa sulkea.

**Comment by kkujansuu** [comment]
OK, kiitos testauksesta.

**Comment by jorma-h** [comment]
Moi!

Minullakin onnistui. "Uusi käyttäjä" sai confirm-sähköpostin, mutta ei 
saanut hyväksytty-postia. Samoin admin ei saanut mitään tietoa 
sähköpostitse.

Voi olla, että sähköposteissa on jotain viivettä.

Jorma

**Comment by jpek-m** [comment]
Näyttöjen tekstit (nimet, linkit, kuvaukset) on tarkastettava ja yhdenmukaistettava @PeterJPower . 
**Korjausehdotukset** ensin dokumenttiin [Asiakkaan rekisteröitymisprosessi 2020](https://docs.google.com/document/d/1MpzByM81Vq48S1ZhRM41NSj-dGZh3Ds8FR_8CPfac28/edit#heading=h.395z7qq9o6o7), minkä jälkeen muutokset ohjelmoidaan.

**Comment by jpek-m** [comment]
Näyttää valmistuneen 2020 aikana, @PeterJPower ja @jorma-h  säätivät tekstejä.

**Comment by jpek-m** [comment]
Isotestissä rekisteröitymisen viimeinen vaihe antaa virheen, kun admin painaa sähköpostissa linkkiä
`Approve user: http://isotest.isotammi.net/admin/update_user/jpek-7`. 

- **Admin** saapuu liittymislomakkeelle kirjautuneena **uutena käyttäjänä**, eikä hänellä ole siihen oikeutta.
- Uuden käyttäjän rooli ei ole muuttunut (hän itse joutuu myös aina liittymislomakkeelle

![2021-01-15 Liity Isotammeen  - 🌳Isotest](https://user-images.githubusercontent.com/9086853/104747974-d8723000-5759-11eb-8d76-d77996c5d0ee.png)

**Comment by jpek-m** [comment]
Toimii oikein, kun tarkennetaan työnkulkua: 

- Kun admin saa sähköpostin otsikolla _New user request for Isotammi_, pitää varmistaa, ettei selaimella ole ei-admin -istuntoa käynnissä ennenkuin klikkaa _Approve user_ -linkkiä.
