### ISSUE TITLE
Hyväksytyn aineiston poistaminen

### ISSUE THREAD

**Issue by jpek-m** [Taapeli/stk-upload#61]
Nyt kehitysvaiheessa ainakin tarvitaan toiminto, jolla **hyväksytty aineistoerä poistetaan kannasta**. Toteutus persutuisi tämäntapaiseen Cypher-lauseeseen (tosin ei kaikki nodet samassa lauseessa, tulee liian iso):
```
MATCH (a:Audit {id:"2020-07-25.001"}) -[:PASSED]-> (x)
DETACH DELETE x
```
Eräänlainen malli erän palastelusta löytyy ohjelmasta `bp.audit.models.batch_merge.Batch_merge.move_whole_batch`. (Toinen mahdollisuus rajata määrää on laittaa vaan LIMIT 400, tosin silloin kunkin kierroksen suorituksen (=commit) välillä kannan tilanne voi olla jonkin verran risa.)

Toiminnon käynnistyksen voisi laittaa sivulle _Isotammen aineistoerät ja kohteiden lukumäärä_ `/audit/approvals/all`.

**Comment by hexaroi** [comment]
Yritin assignata itselleni, mutta taitaa voimat olla liian vähäiset.
