### ISSUE TITLE
Toimistolle lupa katsella tarjokasaineistoa

### ISSUE THREAD

**Issue by kkujansuu** [Taapeli/stk-upload#7]
Tarjokasaineistojen yhteydessä pitäisi käyttäjällä myös olla mahdollisuus sallia se että "tukitoimisto voi tarkastella (ja downloadata) tutkijan lataamaa tarjokasaineistoa". Siis vastaava ruksi kuin gedcomien yhteydessä.

Mihin tämä tieto sitten talletettaisiin? Liittyykö se jo tutkijan lataamaan XML-tiedostoon vai vasta siihen vaiheeseen kun ko. tiedosto on ladattu kantaan (ts. on muodostettu Batch-noodi)? Ja miten sitten estettäisiin se ettei "toimisto" näe ko. aineistoa jos se on kannassa?

**Comment by jpek-m** [comment]
Tallettaisin toimiston katseluluvan Batch-noodiin. Otan mukaan suunnitteluun.

**Comment by kkujansuu** [comment]
PekkaV:

"Ajattelin, että ruksattu Gramps XML talletetaan omana tiedostonaan kuten gedcom-tiedostot. Tiedoston lataus tuen omalle koneelle olisi tarpeen, jos Isotammen näytöistä ei saa tarkkaa kuvaa alkuperäisestä ainiestosta. Silloin tuki voisi avata ladatun XML:n Grampsiinsä ja katsoa dataa siinä. Menettely on tarpeen testauksen varmistamiseksikin.

Ehkä ruksikin on tarpeeton, tallentamisen ja alaslatauksen voisi sallia aina tuelle.

Oli tarkoitus muutenkin miettiä tarjokasaineistojen näkymiä. Nythän siinä muistaakseni tutkija voi katsoa omia aineistojaan demokannan (Isotammen?) aineistojen rinnalla.  Tuki tarvitsisi ehkä mahdollisuuden katsoa mitä tahansa tarjoakasaineistoa muiden aineistojen rinnalla, hakea päällekkäisyyksiä jne. "

**Comment by kkujansuu** [comment]
Ei totetuteta koska toimistolla on aika oikeus katsella!
