### ISSUE TITLE
Versiot-sivun vertailu kaatuu, jos on vain yksi gedcom-versio 

### ISSUE THREAD

**Issue by jpek-m** [Taapeli/stk-upload#8]
Uuden (muokkaamattoman) gedcom-tiedoston tapauksessa _Versiot_-sivulla ei ole oletuksena valittu vertailtavaa tiedostoa. Silti näkyvillä on _Vertaile versioita_ -nappi, jota painettaessa tulee punainen ilmoitus "Palvelinvirhe".

Korjaaminen voitaisiin tehdä kätkemällä vertailupainike (jos mahdollista). 

Mikäli se on hankalaa, voidaan myös käsitellä painikkeen painallus joko ilman reaktiota, antaen äänimerkki tai näyttämällä virheilmoitus (painikkeen alla tai pop-up ?).

**Comment by kkujansuu** [comment]
Tämän piti toimia niin, ja niin se oli koodattu, että ko. painike olisi disabloitu, jos versioita on vain yksi. Mutta tämä ei näytä enää toimivan - ja se johtuu luultavasti siitä että yritin olla fiksu ja muutin painikkeet jossain vaiheessa CSS:llä tehdyiksi <btn>-elementeiksi - ja luultavasti javascriptillä tehty disablointi ei toimikaan niille!

Korjasin nyt niin että jos versioita on vain yksi niin oletuksena se on valittuna molemmissa sarakkeissa, jolloin tiedostoa vertaillaan itseensä. Ei ainakaan kaadu enää.

**Comment by kkujansuu** [comment]
No yhtä helppoa olisi kyllä piilottaa painike, jos versioita on vain yksi. Tai itse asiassa molemmat painikkeet, se toinen painike poistaa vanhat versioita ja niitä ei siinä tapauksessa ole. 

Kumpikohan olisi parempi? Laatikko on kyllä vähän tyhjän näköinen jos siinä ei ole yhtään painiketta.

**Comment by jpek-m** [comment]
Ehdotan, että poistetaan painikkeet ja lisätään teksti "Ei versioita"

**Comment by kkujansuu** [comment]
> Ehdotan, että poistetaan painikkeet ja lisätään teksti "Ei versioita"

Tehty niin.
